#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("IRMGARD.Resource", IsApplication=true)]

namespace IRMGARD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public const int activity_horizontal_margin = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int activity_vertical_margin = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_help_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_volume_up_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int irmgard_picture = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int btnHint = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int btnNextLesson = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int btnPreviousLesson = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int btnStart = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int btnVoiceInstruction = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int checkBox1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int checkBox2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int frameLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int imageView1 = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int lvLevels = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LessonFrame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LevelSelect = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int levelFrame_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int hint = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int playVoiceInstruction = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
