#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IRMGARD.Resource", IsApplication=true)]

namespace IRMGARD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int light_gray = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int activity_horizontal_margin = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int activity_vertical_margin = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_forward_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_help_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_play_arrow_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_volume_up_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int irmgard_picture = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int list_selector = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int btnCheck = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int btnFinish = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int btnHint = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int btnNextLesson = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int btnNextModule = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int btnPreviousLesson = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int btnPreviousModule = 2131230741;
			
			// aapt resource value: 0x7f08000d
			public const int btnStart = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int btnVoiceInstruction = 2131230736;
			
			// aapt resource value: 0x7f080008
			public const int fragmentContainer = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int gvFourPictures = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int imageView1 = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int ivMeidaElementImage = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout1 = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int lvLevels = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int lvModules = 2131230735;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int tvLetter = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int txtCapitalAlphabet = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int txtLessonNumber = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int txtLowerAlphabet = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int txtModuleNumber = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FourPictures = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HearMe = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LessonFrame = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LevelSelect = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MediaElement = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ModuleSelect = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int levelFrame_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int error_soundfileNotFound = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int hint = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int playVoiceInstruction = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
