#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IRMGARD.Resource", IsApplication=true)]

namespace IRMGARD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int debugDraw = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int horizontalSpacing = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int layout_horizontalSpacing = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int layout_newLine = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int layout_verticalSpacing = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int orientation = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int verticalSpacing = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int irmgard_red = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int irmgard_red_dark = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int light_gray = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int activity_horizontal_margin = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int activity_vertical_margin = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int divider = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dotted = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_arrow_forward_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_chat_bubble_outline_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_help_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_play_arrow_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_volume_up_black_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int irmgard_picture = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int list_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splashscreen = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sponsor_koenigsdruck_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sponsor_lions_logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sponsor_veolia_logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sponsoren_level_1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Text = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int underscore = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0009
			public const int abcRankElementName = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int abcRankMeidaElementImage = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int abcRankSolutionElementName = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int btnCheck = 2131361796;
			
			// aapt resource value: 0x7f0a001e
			public const int btnClose = 2131361822;
			
			// aapt resource value: 0x7f0a0027
			public const int btnNext = 2131361831;
			
			// aapt resource value: 0x7f0a0029
			public const int btnNextLesson = 2131361833;
			
			// aapt resource value: 0x7f0a002b
			public const int btnNextModule = 2131361835;
			
			// aapt resource value: 0x7f0a002a
			public const int btnPreviousLesson = 2131361834;
			
			// aapt resource value: 0x7f0a002c
			public const int btnPreviousModule = 2131361836;
			
			// aapt resource value: 0x7f0a0026
			public const int btnRepeat = 2131361830;
			
			// aapt resource value: 0x7f0a0020
			public const int btnStart = 2131361824;
			
			// aapt resource value: 0x7f0a0028
			public const int btnVoiceInstruction = 2131361832;
			
			// aapt resource value: 0x7f0a000c
			public const int flLetters = 2131361804;
			
			// aapt resource value: 0x7f0a0017
			public const int fragmentContainer = 2131361815;
			
			// aapt resource value: 0x7f0a0010
			public const int gvFourPictures = 2131361808;
			
			// aapt resource value: 0x7f0a0012
			public const int hearMeImageView = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int hearMeLetterToLearn = 2131361809;
			
			// aapt resource value: 0x7f0a0013
			public const int hearMeName = 2131361811;
			
			// aapt resource value: 0x7f0a0000
			public const int horizontal = 2131361792;
			
			// aapt resource value: 0x7f0a0014
			public const int imageView1 = 2131361812;
			
			// aapt resource value: 0x7f0a0006
			public const int ivAbcRankSolutionItem = 2131361798;
			
			// aapt resource value: 0x7f0a000f
			public const int ivMeidaElementImage = 2131361807;
			
			// aapt resource value: 0x7f0a0023
			public const int ivPickSyllableDropZone = 2131361827;
			
			// aapt resource value: 0x7f0a001f
			public const int linearLayout1 = 2131361823;
			
			// aapt resource value: 0x7f0a0005
			public const int llLayout = 2131361797;
			
			// aapt resource value: 0x7f0a000a
			public const int llSoundItems = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int llTaskItems = 2131361803;
			
			// aapt resource value: 0x7f0a001a
			public const int longIndicator = 2131361818;
			
			// aapt resource value: 0x7f0a001c
			public const int lvLevels = 2131361820;
			
			// aapt resource value: 0x7f0a0021
			public const int lvModules = 2131361825;
			
			// aapt resource value: 0x7f0a0024
			public const int pickSyllableTaskItems = 2131361828;
			
			// aapt resource value: 0x7f0a0003
			public const int rankTaskItems = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int resolvedRankTaskItems = 2131361794;
			
			// aapt resource value: 0x7f0a001b
			public const int shortIndicator = 2131361819;
			
			// aapt resource value: 0x7f0a000e
			public const int tvAddMultiIcon = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int tvLetter = 2131361805;
			
			// aapt resource value: 0x7f0a0022
			public const int tvPickSyllable = 2131361826;
			
			// aapt resource value: 0x7f0a001d
			public const int tvSponsorText = 2131361821;
			
			// aapt resource value: 0x7f0a0018
			public const int txtCapitalAlphabet = 2131361816;
			
			// aapt resource value: 0x7f0a0016
			public const int txtLessonNumber = 2131361814;
			
			// aapt resource value: 0x7f0a0019
			public const int txtLowerAlphabet = 2131361817;
			
			// aapt resource value: 0x7f0a0015
			public const int txtModuleNumber = 2131361813;
			
			// aapt resource value: 0x7f0a0001
			public const int vertical = 2131361793;
			
			// aapt resource value: 0x7f0a0025
			public const int videoView = 2131361829;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AbcRank = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AbcRankSolutionItems = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AbcRankTaskItems = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BuildSyllable = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BuildSyllableLetterTaskItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BuildSyllableMediaElement = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FindMissingLetter = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FourPictures = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HearMe = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LessonFrame = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Letter = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LetterDrop = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LetterTaskItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LevelSelect = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LevelSponsor = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Main = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int MediaElement = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ModuleSelect = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PickSyllable = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int PickSyllableTaskItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Video = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int levelFrame_menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Handy_Modul_1_720p = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int close = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int error_soundfileNotFound = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int hint = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int playVoiceInstruction = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int sponsor_welcome = 2131165190;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int IrgmgardActionBar = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int IrmgardTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlowLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 3
			public const int FlowLayout_debugDraw = 3;
			
			// aapt resource value: 0
			public const int FlowLayout_horizontalSpacing = 0;
			
			// aapt resource value: 2
			public const int FlowLayout_orientation = 2;
			
			// aapt resource value: 1
			public const int FlowLayout_verticalSpacing = 1;
			
			public static int[] FlowLayout_LayoutParams = new int[] {
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public const int FlowLayout_LayoutParams_layout_horizontalSpacing = 1;
			
			// aapt resource value: 0
			public const int FlowLayout_LayoutParams_layout_newLine = 0;
			
			// aapt resource value: 2
			public const int FlowLayout_LayoutParams_layout_verticalSpacing = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
